### ISSUE TITLE
don't have post.xml

### ISSUE THREAD

**Issue by Riku-tei** [ahmadreza-smdi/RFM_Implementation#1]
Recently I also do a research on RFM model and find your implementation of the paper,I try to run this code but it seems that you didn't upload post.xml so  i don't have data to  run this model .can you remove post.xml from .gitignore and upload it again? I promise that I won't use this data for any other illegal purpose.I just want to run it as a demo thus think a way to improve it .thank you in advance.

**Comment by ahmadreza-smdi** [comment]
sure, no problem. there isn't sensitive data within that file. send me your email and I'll email you some sample dataset to work with.

**Comment by Riku-tei** [comment]
thank you very much! and my email address is
teishouu@yahoo.co.jp
